<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Unknown Error' => 'Unknown reason error, Contact with Administrator',
    'Duplicated Submit' => 'Duplicated Submit',
    'Action' => '',
    'Audit Module' => '',
    'BCC' => '',
    'CC' => '',
    'Created' => '',
    'Data' => '',
    'Duration' => '',
    'Emailed' => '',
    'Entries' => '',
    'Entry ID' => '',
    'Error Code' => '',
    'Field' => '',
    'File' => '',
    'From' => '',
    'Guest' => '',
    'HTML Body' => '',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Line' => '',
    'Memory' => '',
    'Message' => '',
    'New Value' => '',
    'Old Value' => '',
    'Origin' => '',
    'Reply' => '',
    'Request Method' => '',
    'Subject' => '',
    'Create a new Board Successful' => 'Create a new Board Successful',
    'Text Body' => '',
    'To' => '',
    'Trace' => '',
    'Type' => '',
    'User' => '',
    'User ID' => '',
];
